// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Chaminda Perera",
    email: "chaminda.perera@edu.lk",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5678",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Galle Road, Colombo 03, Sri Lanka",
  },
  {
    id: 2,
    teacherId: "1234567891",
    name: "Samanthi Silva",
    email: "samanthi.silva@edu.lk",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5679",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "456 Kandy Road, Peradeniya, Sri Lanka",
  },
  {
    id: 3,
    teacherId: "1234567892",
    name: "Nuwan Gamage",
    email: "nuwan.gamage@edu.lk",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5680",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "789 Nugegoda, Colombo, Sri Lanka",
  },
  {
    id: 4,
    teacherId: "1234567893",
    name: "Kasun Fernando",
    email: "kasun.fernando@edu.lk",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5681",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "12 Parliament Road, Battaramulla, Sri Lanka",
  },
  {
    id: 5,
    teacherId: "1234567894",
    name: "Anusha Jayasuriya",
    email: "anusha.jayasuriya@edu.lk",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5682",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "34 Kotte Road, Nugegoda, Sri Lanka",
  },
  {
    id: 6,
    teacherId: "1234567895",
    name: "Dilani Perera",
    email: "dilani.perera@edu.lk",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5683",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "56 Kirulapone, Colombo, Sri Lanka",
  },
  {
    id: 7,
    teacherId: "1234567896",
    name: "Ruwan Weerasinghe",
    email: "ruwan.weerasinghe@edu.lk",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5684",
    subjects: ["English"],
    classes: ["5A", "4B", "3C"],
    address: "78 Rajagiriya, Colombo, Sri Lanka",
  },
  {
    id: 8,
    teacherId: "1234567897",
    name: "Ishara Karunaratne",
    email: "ishara.karunaratne@edu.lk",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5685",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "89 Dehiwala, Colombo, Sri Lanka",
  },
  {
    id: 9,
    teacherId: "1234567898",
    name: "Tharindu Rathnayake",
    email: "tharindu.rathnayake@edu.lk",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5686",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "90 Kandy Road, Colombo, Sri Lanka",
  },
  {
    id: 10,
    teacherId: "1234567899",
    name: "Manori Wijesinghe",
    email: "manori.wijesinghe@edu.lk",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+94 71 234 5687",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Fort, Colombo, Sri Lanka",
  },
];


export const studentsData = [
  {
    id: 1,
    studentId: "S1234567",
    name: "Kavindu Perera",
    email: "kavindu.perera@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0771234567",
    grade: 10,
    class: "10B",
    address: "No. 10, Galle Road, Colombo 03, Sri Lanka",
  },
  {
    id: 2,
    studentId: "S2345678",
    name: "Samanthi Silva",
    email: "samanthi.silva@yahoo.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0772345678",
    grade: 11,
    class: "11A",
    address: "No. 45, Kandy Road, Kandy, Sri Lanka",
  },
  {
    id: 3,
    studentId: "S3456789",
    name: "Nimal Wickramasinghe",
    email: "nimal.wickramasinghe@hotmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0773456789",
    grade: 12,
    class: "12C",
    address: "No. 78, Station Road, Jaffna, Sri Lanka",
  },
  {
    id: 4,
    studentId: "S4567890",
    name: "Chathurika Jayawardena",
    email: "chathurika.jayawardena@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0774567890",
    grade: 9,
    class: "9D",
    address: "No. 12, Main Street, Gampaha, Sri Lanka",
  },
  {
    id: 5,
    studentId: "S5678901",
    name: "Ruwan Gunawardena",
    email: "ruwan.gunawardena@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0775678901",
    grade: 8,
    class: "8B",
    address: "No. 34, Temple Road, Matara, Sri Lanka",
  },
  {
    id: 6,
    studentId: "S6789012",
    name: "Nirosha Fonseka",
    email: "nirosha.fonseka@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0776789012",
    grade: 7,
    class: "7A",
    address: "No. 56, Beach Road, Negombo, Sri Lanka",
  },
  {
    id: 7,
    studentId: "S7890123",
    name: "Lakshan Abeysekera",
    email: "lakshan.abeysekera@outlook.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0777890123",
    grade: 10,
    class: "10E",
    address: "No. 67, Hospital Road, Nugegoda, Sri Lanka",
  },
  {
    id: 8,
    studentId: "S8901234",
    name: "Ayesha De Silva",
    email: "ayesha.desilva@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0778901234",
    grade: 6,
    class: "6C",
    address: "No. 89, Park Lane, Kurunegala, Sri Lanka",
  },
  {
    id: 9,
    studentId: "S9012345",
    name: "Dulshan Fernando",
    email: "dulshan.fernando@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0779012345",
    grade: 11,
    class: "11B",
    address: "No. 23, Queen's Road, Trincomalee, Sri Lanka",
  },
  {
    id: 10,
    studentId: "S0123456",
    name: "Sachini Rathnayake",
    email: "sachini.rathnayake@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0770123456",
    grade: 9,
    class: "9A",
    address: "No. 90, Lake Road, Anuradhapura, Sri Lanka",
  },
];


export const parentsData = [
  {
    id: 1,
    name: "Nimal Perera",
    students: ["Surangi Perera"],
    email: "nimal@perera.lk",
    phone: "0771234567",
    address: "No. 45, Galle Road, Colombo 3, Sri Lanka",
  },
  {
    id: 2,
    name: "Kumari Fernando",
    students: ["Chathura Fernando"],
    email: "kumari@fernando.lk",
    phone: "0712345678",
    address: "No. 10, Kandy Road, Kandy, Sri Lanka",
  },
  {
    id: 3,
    name: "Samantha Silva",
    students: ["Dinusha Silva"],
    email: "samantha@silva.lk",
    phone: "0779876543",
    address: "No. 23, Dharmapala Mawatha, Gampaha, Sri Lanka",
  },
  {
    id: 4,
    name: "Ruwan Jayasinghe",
    students: ["Iresha Jayasinghe", "Ishan Jayasinghe"],
    email: "ruwan@jayasinghe.lk",
    phone: "0718765432",
    address: "No. 7, Matara Road, Galle, Sri Lanka",
  },
  {
    id: 5,
    name: "Anula Rathnayake",
    students: ["Shanika Rathnayake"],
    email: "anula@rathnayake.lk",
    phone: "0762345678",
    address: "No. 12, Ananda Mawatha, Kurunegala, Sri Lanka",
  },
  {
    id: 6,
    name: "Chandana de Silva",
    students: ["Kasun de Silva"],
    email: "chandana@desilva.lk",
    phone: "0719876543",
    address: "No. 22, Station Road, Negombo, Sri Lanka",
  },
  {
    id: 7,
    name: "Thilini Wijesekara",
    students: ["Lasith Wijesekara", "Mihiri Wijesekara"],
    email: "thilini@wijesekara.lk",
    phone: "0774567890",
    address: "No. 34, Pallekelle, Kandy, Sri Lanka",
  },
  {
    id: 8,
    name: "Sunil Bandara",
    students: ["Ruwan Bandara"],
    email: "sunil@bandara.lk",
    phone: "0723456789",
    address: "No. 9, Polonnaruwa Road, Polonnaruwa, Sri Lanka",
  },
  {
    id: 9,
    name: "Madhavi Senanayake",
    students: ["Sanduni Senanayake", "Naduni Senanayake"],
    email: "madhavi@senanayake.lk",
    phone: "0711234567",
    address: "No. 17, Anuradhapura Road, Anuradhapura, Sri Lanka",
  },
  {
    id: 10,
    name: "Asoka Karunaratne",
    students: ["Sithara Karunaratne"],
    email: "asoka@karunaratne.lk",
    phone: "0776543210",
    address: "No. 2, Temple Road, Nuwara Eliya, Sri Lanka",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "Mathematics",
    teachers: ["Nimal Perera", "Samanthi Jayawardena"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Kumari Fernando", "Ruwan Dias"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Chandana Silva", "Sunil Wijesekara"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Mahesh Gunawardena", "Nilakshi Fernando"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Anusha De Silva", "Kasun Rathnayake"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Madhavi Senanayake", "Chinthaka Bandara"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Sunethra Jayasinghe", "Dulani Fernando"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Vimukthi Rathnayake", "Nadeesha Jayasekara"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Ishara Perera", "Dilini Rathnayake"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Chamara Gamage", "Tharanga Fernando"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Nuwan Perera",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Ruwan Fernando",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Thilini Jayawardena",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Sunil Jayasinghe",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Madhavi Senanayake",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Dulani Perera",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Kumudu Rathnayake",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Chathura Silva",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Kasun Wijesekara",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ishara Fernando",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Nuwan Perera",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Sajini Fernando",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Chathurika Wijesekara",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Sunil Jayasinghe",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Madhavi Senanayake",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Lalani Jayawardena",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Kumudu Rathnayake",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Kasun Wijesekara",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Chathura Silva",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Ishara Fernando",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Nimal Perera",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Lakshmi Fernando",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Suranga Jayawardena",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Shantha Senanayake",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Malika Silva",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ruwan Jayasuriya",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Indrani Rathnayake",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Chandana Wijesinghe",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Thilini Wijekoon",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ishara Fernando",
    date: "2025-01-01",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Nimal Perera",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Lakshmi Fernando",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Suranga Jayawardena",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Shantha Senanayake",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Malika Silva",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ruwan Jayasuriya",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Indrani Rathnayake",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Chandana Wijesinghe",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Thilini Wijekoon",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ishara Fernando",
    dueDate: "2025-01-01",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Nimal Perera",
    student: "Saman Perera",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Lakshmi Fernando",
    student: "Kavinda Silva",
    date: "2025-01-01",
    type: "exam",
    score: 85,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Suranga Jayawardena",
    student: "Niroshan Kumara",
    date: "2025-01-01",
    type: "exam",
    score: 88,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Shantha Senanayake",
    student: "Amal Karunaratne",
    date: "2025-01-01",
    type: "exam",
    score: 92,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Malika Silva",
    student: "Isuri Fernando",
    date: "2025-01-01",
    type: "exam",
    score: 75,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ruwan Jayasuriya",
    student: "Nuwan De Silva",
    date: "2025-01-01",
    type: "exam",
    score: 83,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Indrani Rathnayake",
    student: "Kasun Rathnayake",
    date: "2025-01-01",
    type: "exam",
    score: 89,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Chandana Wijesinghe",
    student: "Lakshan Fernando",
    date: "2025-01-01",
    type: "exam",
    score: 87,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Thilini Wijekoon",
    student: "Sandun Rathnayake",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ishara Fernando",
    student: "Dilani Fernando",
    date: "2025-01-01",
    type: "exam",
    score: 88,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Trip to Kandy Lake",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Galle Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip to Negombo",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "National Museum Visit",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Colombo Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magic Show in Kandy",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Trip to Nuwara Eliya Lake",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race in Colombo",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition in Galle",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "National Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];


export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Sinhala Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Science Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Tamil Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C History Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Geography Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Science Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Music Test",
    class: "1C",
    date: "2025-01-01",
  },
];



// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 27, 8, 0),  // August 27, 2024
    end: new Date(2024, 7, 27, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 27, 9, 0),
    end: new Date(2024, 7, 27, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 27, 10, 0),
    end: new Date(2024, 7, 27, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 27, 11, 0),
    end: new Date(2024, 7, 27, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 27, 13, 0),
    end: new Date(2024, 7, 27, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 27, 14, 0),
    end: new Date(2024, 7, 27, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 28, 9, 0),  // August 28, 2024
    end: new Date(2024, 7, 28, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 28, 10, 0),
    end: new Date(2024, 7, 28, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 28, 11, 0),
    end: new Date(2024, 7, 28, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 28, 14, 0),
    end: new Date(2024, 7, 28, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 29, 8, 0),  // August 29, 2024
    end: new Date(2024, 7, 29, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 29, 10, 0),
    end: new Date(2024, 7, 29, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 29, 13, 0),
    end: new Date(2024, 7, 29, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 29, 14, 0),
    end: new Date(2024, 7, 29, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 30, 9, 0),  // August 30, 2024
    end: new Date(2024, 7, 30, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 30, 10, 0),
    end: new Date(2024, 7, 30, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 30, 11, 0),
    end: new Date(2024, 7, 30, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 30, 14, 0),
    end: new Date(2024, 7, 30, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 31, 8, 0),  // August 31, 2024
    end: new Date(2024, 7, 31, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 31, 9, 0),
    end: new Date(2024, 7, 31, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 31, 11, 0),
    end: new Date(2024, 7, 31, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 31, 13, 0),
    end: new Date(2024, 7, 31, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 31, 14, 0),
    end: new Date(2024, 7, 31, 14, 45),
  },
];

